name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
        use-cross: [false, true, true, true, true]
        extension: ["", "", "", "", ""]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract crate name
        run: |
          echo "CRATE_NAME=$(sed -n 's/^name *= *\"\(.*\)\"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV

      - name: Install toolchain & targets
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: ${{ matrix['use-cross'] }}

      - name: Rename artifacts
        run: |
          mkdir -p dist
          mv target/${{ matrix.target }}/release/${{ env.CRATE_NAME }} \
             dist/${{ env.CRATE_NAME }}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}

      - name: Publish Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ env.CRATE_NAME }}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}