name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build release binary
        run: cargo build --release

      - name: Archive release binary
        run: |
          mkdir dist
          cp target/release/gpu-monitor dist/
          cd dist && tar czvf gpu-monitor.tar.gz gpu-monitor

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/gpu-monitor.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}